### ISSUE TITLE
Make cmake build libaria2.

### ISSUE THREAD

**Issue by mjstahlberg** [Unvanquished/updater#29]
Also it should print a human readable warning when the git submodule isn't initialized or maybe even perform the initialization.

**Comment by slipher** [comment]
Now that we are using Qt which is difficult to install, we want to be able to use the Docker build during development. Since aria takes longer to build than our code, and rarely changes, it is desirable to build in a separate Docker layer earlier than the one in which our code is built. This is probably impossible if we integrate the commands into the qmake (what we are using now instead of cmake) build system. Hence, shelling out from the main build system to build aria is now undesirable.
