### ISSUE TITLE
[Windows 10] Updater loading forever

### ISSUE THREAD

**Issue by GamesOpenSource** [Unvanquished/updater#36]
The (assumed news) widget in the center never loads.

![image](https://user-images.githubusercontent.com/54016023/63015187-97089180-be90-11e9-9927-bcbcfcaa1172.png)

Also, the area at the bottom contains no content - only if you press the download icon (which is in the screenshot replaced by the play icon) then that area contains information.

Not sure whether these are technological or usability issues.

EDIT: here's a video https://www.youtube.com/watch?v=_0HEZzBGZbg

**Comment by slipher** [comment]
I wonder if the news could be another HTTPS redirect issue?

**Comment by illwieckz** [comment]
The http://www.unvanquished.net/?json=get_recent_posts url (used by updater) was kept available with http protocol and www prefix without any redirection on purpose. So unless I missed another url, the problem seems to be elsewhere. I know that after enabled this URL on http, I tested both Linux and Window (running on wine) updater and they both fetched the latest news but failed to fetch the older ones for an unknown reason. I don't have windows machine right to me at this time to do more tests.

Note that the json file references images with https protocol and we know the windows build of the updater does not support https yet. I don't know how would behaves the updater in this case: displays nothing or display the blog post without image, it would be the later since the blog post is successfully fetched in any way.

**Comment by GamesOpenSource** [comment]
Just in case:

The following URLs work as they are:
https://unvanquished.net/?json=get_recent_posts
https://www.unvanquished.net/?json=get_recent_posts
http://www.unvanquished.net/?json=get_recent_posts

http://unvanquished.net/?json=get_recent_posts seems to redirect to https://unvanquished.net/?json=get_recent_posts

(in chrome)

**Comment by illwieckz** [comment]
This is expected because that's what is written in config files _on purpose_, we don't have to care about redirects on anything else than `http://www` because this is the url hardcoded in the current updater (until any update that would change it) and because the updater does not handle redirects. Others scenarios are not useful to this thread.

**Comment by illwieckz** [comment]
OK, I did a lot of dark margic with nginx, rewriting the wordpress' json on the fly when fetched the way the updater fetches it, i.e. replacing the images url with `http://www` when json is fetched with `http://www`, and enabling images to be fetched the http with www way.

This seems to work. The older news (when clicking "right arrow") is still not displayed and I guess it's that because the json sets `null` for the thumbnail, and it looks like the updater does not display the blog post at all if the thumbnail is missing. There is other ways to get thumbnails from json, so before trying to fix wordpress database, I keep the issue so we can investigate. In any way it does not prevent to display the *current* blog post.

**Comment by illwieckz** [comment]
usability issue is tracked in #42, the technical one seems to be fixed as seen on discord today (screenshot by @GamesOpenSource) :

![updater](https://user-images.githubusercontent.com/2311649/63203526-35af1100-c090-11e9-8529-88a60ebfc546.png)
