### ISSUE TITLE
Self-update does not work when updater is launched from the zip file (windows allows to browse zip files like directories)

### ISSUE THREAD

**Issue by slipher** [Unvanquished/updater#49]
The updater's self-update functionality (replacing its own binary) does not work when it is launched from a zip file, as the binary path is some temp location.

We currently distribute the updater in a zip file, presumably due to the binary obesity (like 40M IIRC). One option would be try to find some compile flags to reduce the binary size, and then distribute the bare executable.

Another way would be to have the updater properly install itself - copy to the installation directory, create shortcuts etc. This would be a good idea in general since, assuming most users put the updater in the default "Downloads" folder or whatever, it is sketchy to have a non-single-use program located there.

**Comment by illwieckz** [comment]
I've heard that's hard to reduce file size of QML binaries.

That's good you talk about having the updater properly installing itself. I'm thinking about this for weeks (I was just postponing that talk because of all other things I'm already thinking about).

For the next sentences I'll assume Linux (we would adapt for other OS):

Basically what I think is that the updater would install itself as `~/.local/share/unvanquished/base/updater` at first launch and then run it and close the parent, and of course that path would be the updater to update in priority, and every time the original updater is started, whatever it is stored, it would start the one in `~/.local/share/unvanquished/base` before doing anything else. Autogenerated shortcuts would point to the updater in that path, not the randomly downloaded one.

We may also try to replace the binary that is stored in the wild, but even if we fail to, that would not be a problem, starting an old updater will load the newer one even before trying to update.

That would fix the started-from-zip issue at the same time.

**Comment by illwieckz** [comment]
I renamed the title to be more explicit.

**Comment by DolceTriade** [comment]
Updater shouldn't install itself without installing Unvanquished. I think it's wrong to install the updater without explicit user action.

**Comment by slipher** [comment]
> Updater shouldn't install itself without installing Unvanquished. I think it's wrong to install the updater without explicit user action.

Agreed.

For this issue there is a simple solution - distribute the Windows and Linux updaters on the download page as bare executables, not zip files. (It is OK to continue using zips when doing a self-update).

I do want to implement storing the updater inside the install location, but only after the user has started the game download.

**Comment by illwieckz** [comment]
If we distribute the updater outside of a zip, why not using [UPX](https://github.com/upx/upx).

Here are statistics from v0.0.5 updater:

```
$ du -sh updater2-upx updater2 UnvUpdaterLinux.zip | sort -h
12M	updater2-upx
15M	UnvUpdaterLinux.zip
34M	updater2
```

I compressed the binary this way: `upx-ucl --best --lzma -o updater2-upx updater2`

**Comment by slipher** [comment]
@illwieckz I added the bare Windows executable into the v0.0.5 release on Github. Can you change the unvanquished.net/download link to point to that instead of the zip?

Note that the zip on Github will continue to be used for self-updates.

**Comment by slipher** [comment]
Download link is now pointing to the .exe, thanks illwieckz. 

I wonder if this issue could occur on Linux too. There are many file browsers, so there might be one that has the same feature of running a binary by copying it to a temp location. But it's not clear what could be done, since downloading the bare executable doesn't really work either. So I'll close this.
