### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by slipher** [Unvanquished/updater#56]
By statically linking Qt we are "infected" with the GPL, so that would be a logical choice I guess.

There are 2 contributors outside of the core Unvanquished dev team:

```
$ git shortlog -sne
    64  dolcetriade <vcelestialragev@gmail.com>
    21  DolceTriade <vcelestialragev@gmail.com>
    20  Thomas Debesse <dev@illwieckz.net>
    20  slipher <dog964@xemaps.com>
     4  Roman Chistokhodov <freeslave93@gmail.com>
     2  Ryozuki <clud6565@gmail.com>
     1  Thomas Debesse <github@illwieckz.net>
```

**Comment by DolceTriade** [comment]
Did they make any lasting changes? Perhaps we can remove them?

**Comment by slipher** [comment]
We could also consider the MIT license, since I am adding a piece of MIT-licensed code in #58. It is GPL-compatible.

We can at least try to contact them. @FreeSlave @edg-l May we license the code under GPL and/or MIT licenses?

**Comment by illwieckz** [comment]
For FreeSlave, [most commits](https://github.com/Unvanquished/updater/commits?author=FreeSlave) are about the readme and docker files, those commits do not contribute to the binary itself and can't be tainted by GPL, [one commit](https://github.com/Unvanquished/updater/commit/52b69eecaa1a060611a1685414d0cba2041ce262) changes the compiled/executed code though, but it would be hard to call this one original. In this commit one change is about embedding an icon in windows binary the expected way to do it, the other change is making a link clickable and display a hand pointer when hovering the link. On the copyright side this looks to be very basic and done “the way to do it” (it would be like doing `onClick()` in javascript and `hover` CSS class), and on the patent side, idea of displaying a hand hovering a link and opening an url by clicking on a link is not original at all.

For edg-l, [commits](https://github.com/Unvanquished/updater/commits?author=edg-l) are about adding some qml properties in a way it can't be original, and some standard values (1280×720 resolution can't be copyrighted…).

It would be cool to get a waving hand from our friends because it's always nice to do so, would be cool to credit them for making the updater and Unvanquished better, but I would assume nothing is preventing us to produce a build that would taint updater with GPL, at least on this side.

**Comment by edg-l** [comment]
> Ryozuki <clud6565@gmail.com>

This my old name and old mail, sorry for the inconvenience.

As for me, you can license it under GPL or MIT as you like.

**Comment by FreeSlave** [comment]
Hello, I'm fine with that change.

**Comment by ghost** [comment]
This is likely fixed, then?
